-- Security and consistency hardening for the anonymous v1 application.
-- This migration deliberately keeps posts.image_url for compatibility with the current UI.

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

-- ---------------------------------------------------------------------------
-- Supporting tables
-- ---------------------------------------------------------------------------

create table if not exists public.write_rate_events (
  id bigint generated by default as identity primary key,
  scope text not null,
  actor_hash bytea not null,
  created_at timestamptz not null default clock_timestamp()
);

create index if not exists write_rate_events_lookup_idx
  on public.write_rate_events (scope, actor_hash, created_at desc);

create table if not exists public.post_reactions (
  post_id uuid not null references public.posts(id) on delete cascade,
  actor_hash bytea not null,
  kind text not null check (kind in ('confirm', 'like')),
  created_at timestamptz not null default clock_timestamp(),
  primary key (post_id, actor_hash, kind)
);

create table if not exists public.storage_cleanup_queue (
  id bigint generated by default as identity primary key,
  bucket_id text not null,
  object_path text not null,
  reason text not null,
  available_after timestamptz not null default clock_timestamp(),
  created_at timestamptz not null default clock_timestamp(),
  processed_at timestamptz,
  attempts integer not null default 0,
  last_error text,
  unique (bucket_id, object_path)
);

alter table public.write_rate_events enable row level security;
alter table public.post_reactions enable row level security;
alter table public.storage_cleanup_queue enable row level security;

revoke all on public.write_rate_events from anon, authenticated;
revoke all on public.post_reactions from anon, authenticated;
revoke all on public.storage_cleanup_queue from anon, authenticated;

-- ---------------------------------------------------------------------------
-- Hash existing bearer secrets. Legacy RPCs are revoked below, so plaintext is
-- no longer required after the one-way migration.
-- ---------------------------------------------------------------------------

alter table public.post_owners add column if not exists owner_secret_hash bytea;
alter table public.pin_owners add column if not exists owner_secret_hash bytea;

update public.post_owners
set owner_secret_hash = extensions.digest(owner_secret, 'sha256')
where owner_secret_hash is null and owner_secret is not null;

update public.pin_owners
set owner_secret_hash = extensions.digest(owner_secret, 'sha256')
where owner_secret_hash is null and owner_secret is not null;

alter table public.post_owners alter column owner_secret drop not null;
alter table public.pin_owners alter column owner_secret drop not null;

update public.post_owners set owner_secret = null where owner_secret is not null;
update public.pin_owners set owner_secret = null where owner_secret is not null;

alter table public.post_owners alter column owner_secret_hash set not null;
alter table public.pin_owners alter column owner_secret_hash set not null;

revoke all on public.post_owners from anon, authenticated;
revoke all on public.pin_owners from anon, authenticated;

-- ---------------------------------------------------------------------------
-- New writes are constrained immediately. NOT VALID avoids blocking rollout on
-- historical dirty rows; constraints can be VALIDATEd after a cleanup audit.
-- ---------------------------------------------------------------------------

do $migration$
begin
  if not exists (select 1 from pg_constraint where conname = 'posts_lat_v1_check') then
    alter table public.posts add constraint posts_lat_v1_check
      check (lat between -90 and 90) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'posts_lng_v1_check') then
    alter table public.posts add constraint posts_lng_v1_check
      check (lng between -180 and 180) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'posts_category_v1_check') then
    alter table public.posts add constraint posts_category_v1_check check (
      category in ('웨이팅', '혼잡', '사건사고', '교통', '동네질문', '동네소식', '맛집', '일상', '취미')
    ) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'posts_title_v1_check') then
    alter table public.posts add constraint posts_title_v1_check check (
      title is null or char_length(btrim(title)) between 1 and 40
    ) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'posts_content_v1_check') then
    alter table public.posts add constraint posts_content_v1_check check (
      char_length(btrim(content)) between 2 and 500
    ) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'posts_type_v1_check') then
    alter table public.posts add constraint posts_type_v1_check
      check (post_type in ('local', 'external')) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'posts_icon_v1_check') then
    alter table public.posts add constraint posts_icon_v1_check check (
      icon is null or icon in ('pin', 'star', 'alert', 'question', 'food', 'cafe', 'car', 'home', 'heart', 'flag')
    ) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'pins_lat_v1_check') then
    alter table public.pins add constraint pins_lat_v1_check
      check (lat between -90 and 90) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'pins_lng_v1_check') then
    alter table public.pins add constraint pins_lng_v1_check
      check (lng between -180 and 180) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'comments_content_v1_check') then
    alter table public.comments add constraint comments_content_v1_check check (
      char_length(btrim(content)) between 1 and 200
    ) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'chat_content_v1_check') then
    alter table public.chat_messages add constraint chat_content_v1_check check (
      char_length(btrim(content)) between 1 and 300
    ) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'chat_lat_v1_check') then
    alter table public.chat_messages add constraint chat_lat_v1_check
      check (lat between -90 and 90) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'chat_lng_v1_check') then
    alter table public.chat_messages add constraint chat_lng_v1_check
      check (lng between -180 and 180) not valid;
  end if;
end
$migration$;

-- ---------------------------------------------------------------------------
-- Direct writes are closed. SECURITY DEFINER v2 RPCs below are the only write
-- surface. Chat SELECT is also closed because an unrestricted SELECT exposes
-- exact coordinates outside the claimed radius.
-- ---------------------------------------------------------------------------

alter table public.posts enable row level security;
alter table public.pins enable row level security;
alter table public.comments enable row level security;
alter table public.chat_messages enable row level security;

revoke insert, update, delete on public.posts from anon, authenticated;
revoke insert, update, delete on public.pins from anon, authenticated;
revoke insert, update, delete on public.comments from anon, authenticated;
revoke select, insert, update, delete on public.chat_messages from anon, authenticated;

grant select on public.posts to anon, authenticated;
grant select on public.pins to anon, authenticated;
grant select on public.comments to anon, authenticated;

drop policy if exists posts_v1_public_read on public.posts;
create policy posts_v1_public_read on public.posts
  for select to anon, authenticated using (true);

drop policy if exists pins_v1_public_read on public.pins;
create policy pins_v1_public_read on public.pins
  for select to anon, authenticated using (true);

drop policy if exists comments_v1_public_read on public.comments;
create policy comments_v1_public_read on public.comments
  for select to anon, authenticated using (true);

-- Revoke legacy RPCs without assuming their exact argument lists.
do $migration$
declare
  fn record;
begin
  for fn in
    select p.oid::regprocedure as signature
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname in (
        'create_post_with_owner', 'delete_own_post', 'create_pin_with_owner',
        'delete_own_pin', 'delete_expired_pins'
      )
  loop
    execute 'revoke execute on function ' || fn.signature || ' from public, anon, authenticated';
  end loop;
end
$migration$;

-- ---------------------------------------------------------------------------
-- Internal helpers
-- ---------------------------------------------------------------------------

create or replace function public.distance_m_v1(
  p_lat1 double precision,
  p_lng1 double precision,
  p_lat2 double precision,
  p_lng2 double precision
) returns double precision
language sql
immutable
strict
set search_path = pg_catalog
as $function$
  select 6371000 * 2 * asin(sqrt(least(1.0, greatest(0.0,
    power(sin(radians(p_lat2 - p_lat1) / 2), 2) +
    cos(radians(p_lat1)) * cos(radians(p_lat2)) *
    power(sin(radians(p_lng2 - p_lng1) / 2), 2)
  ))));
$function$;

create or replace function public.assert_write_rate_v1(
  p_scope text,
  p_actor_token text,
  p_max_count integer,
  p_window interval
) returns void
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $function$
declare
  v_actor_hash bytea;
  v_count integer;
begin
  if p_actor_token is null or char_length(p_actor_token) < 32 then
    raise exception 'invalid actor token' using errcode = '22023';
  end if;
  if p_max_count < 1 or p_window <= interval '0 seconds' then
    raise exception 'invalid rate limit configuration' using errcode = '22023';
  end if;

  v_actor_hash := extensions.digest(p_actor_token, 'sha256');
  perform pg_advisory_xact_lock(hashtextextended(p_scope || encode(v_actor_hash, 'hex'), 0));

  select count(*) into v_count
  from public.write_rate_events e
  where e.scope = p_scope
    and e.actor_hash = v_actor_hash
    and e.created_at >= clock_timestamp() - p_window;

  if v_count >= p_max_count then
    raise exception 'rate limit exceeded'
      using errcode = 'P0001', hint = 'RATE_LIMIT';
  end if;

  insert into public.write_rate_events(scope, actor_hash)
  values (p_scope, v_actor_hash);
end;
$function$;

create or replace function public.storage_object_path_v1(p_image_url text)
returns text
language sql
immutable
set search_path = pg_catalog
as $function$
  select case
    when p_image_url is null or position('/post-images/' in p_image_url) = 0 then null
    else split_part(split_part(p_image_url, '/post-images/', 2), '?', 1)
  end;
$function$;

revoke all on function public.distance_m_v1(double precision,double precision,double precision,double precision) from public, anon, authenticated;
revoke all on function public.assert_write_rate_v1(text,text,integer,interval) from public, anon, authenticated;
revoke all on function public.storage_object_path_v1(text) from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- Posts: idempotent atomic create, owner-only update/delete, atomic reactions
-- ---------------------------------------------------------------------------

create or replace function public.create_post_v2(
  p_post_id uuid,
  p_actor_token text,
  p_owner_secret text,
  p_author_lat double precision,
  p_author_lng double precision,
  p_lat double precision,
  p_lng double precision,
  p_category text,
  p_title text,
  p_content text,
  p_image_url text default null,
  p_icon text default null
) returns public.posts
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $function$
declare
  v_post public.posts;
begin
  perform public.assert_write_rate_v1('post_create', p_actor_token, 5, interval '10 minutes');

  if p_owner_secret is null or char_length(p_owner_secret) < 32 then
    raise exception 'invalid owner secret' using errcode = '22023';
  end if;
  if p_author_lat not between -90 and 90 or p_author_lng not between -180 and 180
     or p_lat not between -90 and 90 or p_lng not between -180 and 180 then
    raise exception 'invalid coordinates' using errcode = '22023';
  end if;
  if p_image_url is not null
     and position('/storage/v1/object/public/post-images/' in p_image_url) = 0 then
    raise exception 'invalid post image URL' using errcode = '22023';
  end if;

  insert into public.posts (
    id, lat, lng, category, title, content, post_type, image_url, icon, created_at
  ) values (
    p_post_id, p_lat, p_lng, p_category, btrim(p_title), btrim(p_content),
    case when public.distance_m_v1(p_author_lat, p_author_lng, p_lat, p_lng) > 500
      then 'external' else 'local' end,
    p_image_url, p_icon, clock_timestamp()
  )
  on conflict (id) do nothing
  returning * into v_post;

  if v_post.id is null then
    if not exists (
      select 1 from public.post_owners po
      where po.post_id = p_post_id
        and po.owner_secret_hash = extensions.digest(p_owner_secret, 'sha256')
    ) then
      raise exception 'idempotency key already used' using errcode = '23505';
    end if;

    select * into strict v_post from public.posts where id = p_post_id;
    return v_post;
  end if;

  insert into public.post_owners(post_id, owner_secret, owner_secret_hash)
  values (p_post_id, null, extensions.digest(p_owner_secret, 'sha256'));

  return v_post;
end;
$function$;

create or replace function public.update_own_post_v2(
  p_post_id uuid,
  p_owner_secret text,
  p_category text,
  p_title text,
  p_content text,
  p_image_url text default null,
  p_icon text default null
) returns public.posts
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $function$
declare
  v_post public.posts;
  v_old_image_url text;
  v_old_path text;
begin
  if not exists (
    select 1 from public.post_owners po
    where po.post_id = p_post_id
      and po.owner_secret_hash = extensions.digest(p_owner_secret, 'sha256')
  ) then
    raise exception 'not owner' using errcode = '42501';
  end if;
  if p_image_url is not null
     and position('/storage/v1/object/public/post-images/' in p_image_url) = 0 then
    raise exception 'invalid post image URL' using errcode = '22023';
  end if;

  select image_url into v_old_image_url
  from public.posts where id = p_post_id for update;

  update public.posts
  set category = p_category,
      title = btrim(p_title),
      content = btrim(p_content),
      image_url = p_image_url,
      icon = p_icon,
      updated_at = clock_timestamp()
  where id = p_post_id
  returning * into strict v_post;

  if v_old_image_url is distinct from p_image_url and v_old_image_url is not null then
    v_old_path := public.storage_object_path_v1(v_old_image_url);
    if v_old_path is not null then
      insert into public.storage_cleanup_queue(bucket_id, object_path, reason)
      values ('post-images', v_old_path, 'post_image_replaced')
      on conflict (bucket_id, object_path) do update
        set processed_at = null, available_after = clock_timestamp(), last_error = null;
    end if;
  end if;

  return v_post;
end;
$function$;

create or replace function public.delete_own_post_v2(
  p_post_id uuid,
  p_owner_secret text
) returns boolean
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $function$
declare
  v_deleted uuid;
begin
  if not exists (
    select 1 from public.post_owners po
    where po.post_id = p_post_id
      and po.owner_secret_hash = extensions.digest(p_owner_secret, 'sha256')
  ) then
    return false;
  end if;

  delete from public.posts where id = p_post_id returning id into v_deleted;
  return v_deleted is not null;
end;
$function$;

create or replace function public.confirm_post_v2(
  p_post_id uuid,
  p_actor_token text
) returns public.posts
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $function$
declare
  v_inserted integer;
  v_post public.posts;
begin
  perform public.assert_write_rate_v1('post_confirm', p_actor_token, 30, interval '10 minutes');

  if not exists (
    select 1 from public.posts p
    where p.id = p_post_id and p.category in ('웨이팅', '혼잡', '사건사고', '교통')
  ) then
    raise exception 'post does not accept confirmations' using errcode = '22023';
  end if;

  insert into public.post_reactions(post_id, actor_hash, kind)
  values (p_post_id, extensions.digest(p_actor_token, 'sha256'), 'confirm')
  on conflict do nothing;
  get diagnostics v_inserted = row_count;

  if v_inserted = 1 then
    update public.posts p
    set confirm_count = p.confirm_count + 1
    where p.id = p_post_id
    returning * into v_post;
  else
    select * into strict v_post from public.posts where id = p_post_id;
  end if;

  return v_post;
end;
$function$;

create or replace function public.like_post_v2(
  p_post_id uuid,
  p_actor_token text
) returns public.posts
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $function$
declare
  v_inserted integer;
  v_post public.posts;
begin
  perform public.assert_write_rate_v1('post_like', p_actor_token, 30, interval '10 minutes');

  if not exists (
    select 1 from public.posts p
    where p.id = p_post_id and p.category in ('동네질문', '동네소식', '맛집', '일상', '취미')
  ) then
    raise exception 'post does not accept likes' using errcode = '22023';
  end if;

  insert into public.post_reactions(post_id, actor_hash, kind)
  values (p_post_id, extensions.digest(p_actor_token, 'sha256'), 'like')
  on conflict do nothing;
  get diagnostics v_inserted = row_count;

  if v_inserted = 1 then
    update public.posts p
    set likes_count = p.likes_count + 1
    where p.id = p_post_id
    returning * into v_post;
  else
    select * into strict v_post from public.posts where id = p_post_id;
  end if;

  return v_post;
end;
$function$;

-- Queue images whenever a post is deleted, including admin deletions.
create or replace function public.enqueue_deleted_post_image_v1()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_path text;
begin
  v_path := public.storage_object_path_v1(old.image_url);
  if v_path is not null then
    insert into public.storage_cleanup_queue(bucket_id, object_path, reason)
    values ('post-images', v_path, 'post_deleted')
    on conflict (bucket_id, object_path) do update
      set processed_at = null, available_after = clock_timestamp(), last_error = null;
  end if;
  return old;
end;
$function$;

drop trigger if exists posts_enqueue_image_cleanup_v1 on public.posts;
create trigger posts_enqueue_image_cleanup_v1
after delete on public.posts
for each row execute function public.enqueue_deleted_post_image_v1();

-- ---------------------------------------------------------------------------
-- Pins
-- ---------------------------------------------------------------------------

create or replace function public.create_pin_v2(
  p_pin_id uuid,
  p_actor_token text,
  p_lat double precision,
  p_lng double precision,
  p_owner_secret text
) returns public.pins
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $function$
declare
  v_pin public.pins;
begin
  perform public.assert_write_rate_v1('pin_create', p_actor_token, 10, interval '10 minutes');

  if p_owner_secret is null or char_length(p_owner_secret) < 32 then
    raise exception 'invalid owner secret' using errcode = '22023';
  end if;

  insert into public.pins(id, lat, lng, created_at)
  values (p_pin_id, p_lat, p_lng, clock_timestamp())
  on conflict (id) do nothing
  returning * into v_pin;

  if v_pin.id is null then
    if not exists (
      select 1 from public.pin_owners po
      where po.pin_id = p_pin_id
        and po.owner_secret_hash = extensions.digest(p_owner_secret, 'sha256')
    ) then
      raise exception 'idempotency key already used' using errcode = '23505';
    end if;
    select * into strict v_pin from public.pins where id = p_pin_id;
    return v_pin;
  end if;

  insert into public.pin_owners(pin_id, owner_secret, owner_secret_hash)
  values (p_pin_id, null, extensions.digest(p_owner_secret, 'sha256'));
  return v_pin;
end;
$function$;

create or replace function public.delete_own_pin_v2(
  p_pin_id uuid,
  p_owner_secret text
) returns boolean
language plpgsql
security definer
set search_path = pg_catalog, public, extensions
as $function$
declare
  v_deleted uuid;
begin
  if not exists (
    select 1 from public.pin_owners po
    where po.pin_id = p_pin_id
      and po.owner_secret_hash = extensions.digest(p_owner_secret, 'sha256')
  ) then
    return false;
  end if;
  delete from public.pins where id = p_pin_id returning id into v_deleted;
  return v_deleted is not null;
end;
$function$;

create or replace function public.delete_expired_pins_v2()
returns bigint
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_count bigint;
begin
  delete from public.pins where created_at < clock_timestamp() - interval '60 minutes';
  get diagnostics v_count = row_count;
  return v_count;
end;
$function$;

-- ---------------------------------------------------------------------------
-- Comments
-- ---------------------------------------------------------------------------

create or replace function public.create_comment_v2(
  p_comment_id uuid,
  p_post_id uuid,
  p_actor_token text,
  p_content text
) returns public.comments
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_comment public.comments;
begin
  perform public.assert_write_rate_v1('comment_create', p_actor_token, 10, interval '5 minutes');

  insert into public.comments(id, post_id, content, created_at)
  values (p_comment_id, p_post_id, btrim(p_content), clock_timestamp())
  on conflict (id) do nothing
  returning * into v_comment;

  if v_comment.id is null then
    select * into strict v_comment from public.comments where id = p_comment_id;
  end if;
  return v_comment;
end;
$function$;

-- ---------------------------------------------------------------------------
-- Radius-bound chat. Exact chat coordinates are returned only after the server
-- has evaluated the requested radius (capped at 1 km).
-- ---------------------------------------------------------------------------

create index if not exists chat_messages_created_at_v1_idx
  on public.chat_messages(created_at desc);

create or replace function public.get_nearby_chat_messages_v2(
  p_lat double precision,
  p_lng double precision,
  p_radius_meters integer default 1000,
  p_limit integer default 200,
  p_before timestamptz default null
) returns setof public.chat_messages
language sql
stable
security definer
set search_path = pg_catalog, public
as $function$
  select cm.*
  from public.chat_messages cm
  where p_lat between -90 and 90
    and p_lng between -180 and 180
    and p_radius_meters between 1 and 1000
    and (p_before is null or cm.created_at < p_before)
    and public.distance_m_v1(p_lat, p_lng, cm.lat, cm.lng) <= p_radius_meters
  order by cm.created_at desc
  limit least(greatest(p_limit, 1), 200);
$function$;

create or replace function public.send_chat_message_v2(
  p_message_id uuid,
  p_actor_token text,
  p_lat double precision,
  p_lng double precision,
  p_content text
) returns public.chat_messages
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_message public.chat_messages;
begin
  perform public.assert_write_rate_v1('chat_send', p_actor_token, 20, interval '1 minute');

  insert into public.chat_messages(id, lat, lng, content, created_at)
  values (p_message_id, p_lat, p_lng, btrim(p_content), clock_timestamp())
  on conflict (id) do nothing
  returning * into v_message;

  if v_message.id is null then
    select * into strict v_message from public.chat_messages where id = p_message_id;
  end if;
  return v_message;
end;
$function$;

-- ---------------------------------------------------------------------------
-- Public cleanup enqueue is restricted to unreferenced post-images and delayed
-- one hour. The service-role worker MUST re-check references before Storage API
-- removal to close the upload/attach race.
-- ---------------------------------------------------------------------------

create or replace function public.enqueue_storage_cleanup_v1(
  p_bucket_id text,
  p_object_path text,
  p_reason text default 'abandoned_upload'
) returns boolean
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
begin
  if p_bucket_id <> 'post-images'
     or p_object_path is null
     or p_object_path = ''
     or p_object_path like '../%'
     or position('/../' in p_object_path) > 0 then
    raise exception 'invalid storage object' using errcode = '22023';
  end if;
  if p_reason <> 'abandoned_upload' then
    raise exception 'invalid cleanup reason' using errcode = '22023';
  end if;
  if exists (
    select 1 from public.posts p
    where public.storage_object_path_v1(p.image_url) = p_object_path
  ) then
    return false;
  end if;

  insert into public.storage_cleanup_queue(
    bucket_id, object_path, reason, available_after
  ) values (
    p_bucket_id, p_object_path, p_reason, clock_timestamp() + interval '1 hour'
  )
  on conflict (bucket_id, object_path) do update
    set processed_at = null,
        reason = excluded.reason,
        available_after = greatest(public.storage_cleanup_queue.available_after, excluded.available_after),
        last_error = null;
  return true;
end;
$function$;

-- ---------------------------------------------------------------------------
-- Grants: functions are executable by PUBLIC by default, so reset explicitly.
-- ---------------------------------------------------------------------------

revoke all on function public.create_post_v2(uuid,text,text,double precision,double precision,double precision,double precision,text,text,text,text,text) from public;
revoke all on function public.update_own_post_v2(uuid,text,text,text,text,text,text) from public;
revoke all on function public.delete_own_post_v2(uuid,text) from public;
revoke all on function public.confirm_post_v2(uuid,text) from public;
revoke all on function public.like_post_v2(uuid,text) from public;
revoke all on function public.create_pin_v2(uuid,text,double precision,double precision,text) from public;
revoke all on function public.delete_own_pin_v2(uuid,text) from public;
revoke all on function public.delete_expired_pins_v2() from public;
revoke all on function public.create_comment_v2(uuid,uuid,text,text) from public;
revoke all on function public.get_nearby_chat_messages_v2(double precision,double precision,integer,integer,timestamptz) from public;
revoke all on function public.send_chat_message_v2(uuid,text,double precision,double precision,text) from public;
revoke all on function public.enqueue_storage_cleanup_v1(text,text,text) from public;

grant execute on function public.create_post_v2(uuid,text,text,double precision,double precision,double precision,double precision,text,text,text,text,text) to anon, authenticated;
grant execute on function public.update_own_post_v2(uuid,text,text,text,text,text,text) to anon, authenticated;
grant execute on function public.delete_own_post_v2(uuid,text) to anon, authenticated;
grant execute on function public.confirm_post_v2(uuid,text) to anon, authenticated;
grant execute on function public.like_post_v2(uuid,text) to anon, authenticated;
grant execute on function public.create_pin_v2(uuid,text,double precision,double precision,text) to anon, authenticated;
grant execute on function public.delete_own_pin_v2(uuid,text) to anon, authenticated;
grant execute on function public.delete_expired_pins_v2() to anon, authenticated;
grant execute on function public.create_comment_v2(uuid,uuid,text,text) to anon, authenticated;
grant execute on function public.get_nearby_chat_messages_v2(double precision,double precision,integer,integer,timestamptz) to anon, authenticated;
grant execute on function public.send_chat_message_v2(uuid,text,double precision,double precision,text) to anon, authenticated;
grant execute on function public.enqueue_storage_cleanup_v1(text,text,text) to anon, authenticated;
